services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"  # Use APP_PORT or default to 8000
      - "5678:5678"  # Debug port
    volumes:
      - .:/app  # Mount the current directory for hot reload
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=1  # Optional: Add an environment variable for reload
      - DEBUG_IP=${DEBUG_IP}  # Pass the debug IP from the environment
      - APP_PORT=${APP_PORT:-8000}  # Pass the application port
