name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ocr-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ocr-app:latest

      # Deploy the application (optional, replace with your deployment steps)
      # Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Deploy the application
      - name: Deploy application
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}  # Pass the server username as a secret
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Pass the server IP as a secret
          APP_PORT: ${{ secrets.APP_PORT }}  # Pass the application port as a secret
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USERNAME@$SERVER_IP << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/ocr-app:latest
            docker run -d --name ocr-app -p ${APP_PORT}:${APP_PORT} ${{ secrets.DOCKER_USERNAME }}/ocr-app:latest
          EOF

